### ISSUE TITLE
Improve README contents

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/LittleBooks#10]
This includes addressing #5, but also any additional links and/or text we would like to add.  It's pretty minimal at the moment.

**Comment by rpruim** [comment]
Added note about compendium rename

**Comment by nicholasjhorton** [comment]
Closed via https://github.com/ProjectMOSAIC/LittleBooks/commit/813dff0b19d952cda1b8c596bb505340f06df6dc
