### ISSUE TITLE
"Two Audiences" section in "A Student's Guide to R"

### ISSUE THREAD

**Issue by statisfactions** [ProjectMOSAIC/LittleBooks#17]
The "Two Audiences" subsection in the "About These Notes" section of "A Student's Guide to R"  (p. 6) states that the primary audience is instructors.  Is this accurate? Since I thought I was reading a student guide, I found this claim confusing.

**Comment by rpruim** [comment]
You are right.  This document evolved out of one that had a different target audience.  We'll update that section to reflect the current state in the evolution.

**Comment by nicholasjhorton** [comment]
Done.
