### ISSUE TITLE
Declare one of the Modeling versions to be the active one and discard the other

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/LittleBooks#2]
I'm guessing V2 is the one we want.   But neither one compiles as is.  V2 chokes on `proptable()` at the R level.  The other one has lots of LaTeX complaints.

**Comment by nicholasjhorton** [comment]
It would be really neat to revive this (or if it is happening elsewhere, close this issue).  @dtkaplan any thoughts?
