### ISSUE TITLE
vcd causes trouble for mosaic

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/LittleBooks#22]
> require(vcd)
> Loading required package: vcd
> Loading required package: grid

Attaching package: ‘vcd’

The following object is masked from ‘package:mosaic’:

```
mplot
```

Note that vcd is in setup.R!

I've added a "detach(package:vcd)" in TwoQuantitative.Rnw in the StudentGuide, but wanted to alert others.

Caveat emptor.

**Comment by nicholasjhorton** [comment]
Please note: if this package is removed from setup.R, the "detach(package:vcd)" command will need to be removed as it will otherwise throw an error.

**Comment by rpruim** [comment]
I suggest that we don't attach `vcd` but use `vcd::` explicitly if we retain any `vcd` stuff.

**Comment by nicholasjhorton** [comment]
I removed require(vcd) from setup.R.  All looks okay in the StudentGuide.

**Comment by rpruim** [comment]
Just a note:  vcd had already been relegated to a marginal comment in _Start Teaching_.  The old examples of mosaic plots had been commented out earlier.
