### ISSUE TITLE
Pre-printing run-through of Start Teaching

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/LittleBooks#24]
p. 31  `groups = wday` throws an error, since `wday` is not a variable in `Births78`.   Do we want to say
`lubridate::wday(date)`

Same problem with `wday` on pp. 53, 55

I have fixed these provisionally by using
`groups=lubridate::wday(date, label=TRUE)`

Pagination was improved to avoid long blank vertical gaps.  See `\enlargethispage{1in}`

**Comment by rpruim** [comment]
Danny. Please use beta versions of mosaic and mosaicData. I don't think there was any broken code if you have proper packages installed.  I had already repaired things that did not match the beta branches.
