### ISSUE TITLE
add example of horizontal=FALSE into the bwplot discussion of factors in the student guide

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/LittleBooks#26]
Randy suggests:

library(mosaic)
bwplot( birthmonth ~ length, data = KidsFeet)
bwplot( length ~ birthmonth, data = KidsFeet, horizontal = FALSE)

**Comment by nicholasjhorton** [comment]
@rpruim Is this straightforward to do in ggformula?

**Comment by rpruim** [comment]
You can use `factor()`, but using `group` gives you nicer labels.

``` r
library(mosaic)
theme_set(theme_bw())
bwplot( birthmonth ~ length, data = KidsFeet)
```

![](https://i.imgur.com/ivg0XOS.png)

``` r
gf_boxplot(length ~ birthmonth, group = ~birthmonth, data = KidsFeet) %>% 
  gf_refine(coord_flip())
```

![](https://i.imgur.com/6YUu6gc.png)

``` r
bwplot( length ~ birthmonth, data = KidsFeet, horizontal = FALSE)
```

![](https://i.imgur.com/zo4kfwU.png)

``` r
gf_boxplot(length ~ birthmonth, group = ~ birthmonth, data = KidsFeet)
```

![](https://i.imgur.com/dh4X6WT.png)

Created on 2018-06-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
