### ISSUE TITLE
Delete Simulation?  Recommit to it?

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/LittleBooks#3]
The last commit is from over 2 years ago and labeled "toward a first clean compile", so this never was quite ready.  But perhaps it is worth reviving -- have to look at see.  I think this has Danny's Planet Null analogy in it, for example, and removed of the constraints of the Lock bake-off questions, we can organize this differently from the Resampling vignette.

For now, we have the Resampling vignette in the `mosaic` package.

**Comment by rpruim** [comment]
If we bring this back to life, perhaps we can include some information and examples related to Tim Hesterberg's paper.

**Comment by nicholasjhorton** [comment]
I think that this would be valuable.  

Is there a student that might assist?

Just a thought,

Nick

> On May 7, 2015, at 7:48 AM, Randall Pruim notifications@github.com wrote:
> 
> If we bring this back to life, perhaps we can include some information and examples related to Tim Hesterberg's paper.
> 
> —
> Reply to this email directly or view it on GitHub.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by nicholasjhorton** [comment]
I suspect that the Resampling vignette is sufficient so I will be closing this issue.
