### ISSUE TITLE
OneQuantitative Questions

### ISSUE THREAD

**Issue by mchien20** [ProjectMOSAIC/LittleBooks#31]
128. Normal curve looks weird, not sure if there is a function for a normal curve
152. Normal curve looks weird.
178. Dot plot looks strange--might be because I can't get bins to work, so I used binwidth
- also, I can't find 'female' as a data set, not sure if it was filtered and stored somewhere, so I continued to use the filter function for every use.
199. I don't know how to find these functions in ggformula
227. xpnorm gives me a curve that looks like ggplot. Do I need to change this?

**Comment by rpruim** [comment]
Regarding dot plots: `ggplot2` support for dotplots is not that great.  `ggformula` inherits this status.

If you have granular data, setting the binwidth to half of what you think it ought to be often does what you want (due to the default algorithm that `geom_dotplot()` uses).  Or you can the method to "histodot".  Sometimes you also need to fiddle with dot size or axes.  In short, they are a hassle.

**Comment by rpruim** [comment]
`xpnorm()` does give a `ggplot2` plot -- all `ggformula` plots are `ggplot2` plots and that is now the default for `mosaic`-related stuff.

**Comment by rpruim** [comment]
Note:  If you are not working with the latest versions of `mosaic`, `mosaicCore`, and `ggformula`, I encourage you to use the `beta` versions while working on this.  They will be the CRAN versions soon enough -- no sense building documentation for anything older.

**Comment by rpruim** [comment]
For data summaries, are you using `mean()`, *et al* or `df_stats()`?  Which do we want to highlight?

**Comment by nicholasjhorton** [comment]
Margaret, I'm not sure where your questions stand at present: can you please clarify offline?

**Comment by mchien20** [comment]
128. Still not sure how to fix the normal plots
200-205. Not sure how to overlay text on a density plot; not sure about the others either. I know how to add layers with pipes, but I can't figure out this instance
