### ISSUE TITLE
Update CRAN version of LittleBooks

### ISSUE THREAD

**Issue by mchien20** [ProjectMOSAIC/LittleBooks#37]
https://cran.r-project.org/other-docs.html

**Comment by nicholasjhorton** [comment]
Need to address https://github.com/ProjectMOSAIC/LittleBooks/issues/42 and https://github.com/ProjectMOSAIC/LittleBooks/issues/43 prior to submitting (likely ggformula 2.3 issues).

**Comment by nicholasjhorton** [comment]
“A Student's Guide to R” by Nicholas J. Horton, Randall Pruim, and Daniel T. Kaplan (PDF, 2015-11-16, 119 pages) is the old version.

“A Student's Guide to R” by Nicholas J. Horton, Randall Pruim, and Daniel T. Kaplan (PDF, 2018-06-23, 119 pages) is the new version.

**Comment by nicholasjhorton** [comment]
Alas, CRAN has frozen this page so updates are not feasible.  So the pointer from the mosaic-resources vignette will have to suffice.
