### ISSUE TITLE
Compendium creates a PDF but it is a very noisy compile.

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/LittleBooks#4]
It would be nice if this compiled more cleanly.

**Comment by nicholasjhorton** [comment]
I concur.  I'm not sure what to do about it.  At present I'm running the following to get this to compile:

knitr -td MOSAIC-Compendium.Rnw
makeindex MOSAIC-Compendium
pdflatex MOSAIC-Compendium
pdflatex MOSAIC-Compendium

**Comment by rpruim** [comment]
I just compiled with my `knitr -ld MOSAIC-StudentGuide.Rnw` and it when through to completion without any catches or intervention on my part.
