### ISSUE TITLE
gf_text issues

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/LittleBooks#43]
Is this a ggformula problem?

library(mosaic)
panel.labels <- function(x, y, labels = 'x',...) { panel.text(x, y, labels, cex = 0.4, ...)
}

gf_text(Murder ~ Assault, panel = panel.labels,
label = rownames(USArrests), data = USArrests, size = 2)

**Comment by rpruim** [comment]
What are you trying to do?  `gf_text()` does not have a panel argument.

Are any of these what you are after?

``` r
library(ggformula)
#> Loading required package: ggplot2
#> 
#> New to ggformula?  Try the tutorials: 
#>  learnr::run_tutorial("introduction", package = "ggformula")
#>  learnr::run_tutorial("refining", package = "ggformula")
theme_set(theme_bw())
USArrests %>% dplyr::mutate(State = rownames(USArrests)) %>%
  gf_text(Murder ~ Assault, label = "x")
```

<img src="https://i.imgur.com/qA37otN.png" style="display: block; margin: auto;" />

``` r

USArrests %>% dplyr::mutate(State = rownames(USArrests)) %>%
  gf_point(Murder ~ Assault, shape = "x", size = 3)
```

<img src="https://i.imgur.com/GlEmICK.png" style="display: block; margin: auto;" />

``` r

USArrests %>% dplyr::mutate(State = rownames(USArrests)) %>%
  gf_point(Murder ~ Assault, size = 2, alpha = 0.3, color = "red") %>%
  gf_text(Murder ~ Assault, label = ~State, angle = 30, size = 3)
```

<img src="https://i.imgur.com/iHdXHZI.png" style="display: block; margin: auto;" />

Created on 2018-06-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
