### ISSUE TITLE
Broken link to http://www.mosaic-web.org/go/teachingRlicense.html ?

### ISSUE THREAD

**Issue by NMarkgraf** [ProjectMOSAIC/LittleBooks#46]
As far as I can see, the link to http://www.mosaic-web.org/go/teachingRlicense.html is broken, isn't it?

For a possible german translation of the book, we need to know exactly is on the referred webpage, as it might be part of the copyright statement in the book.

Thanks ins advance
N. Markgraf

**Comment by nicholasjhorton** [comment]
Apologies for the delay. I'm not sure what files/URLs are referencing this link. Can you please advise?

**Comment by rpruim** [comment]
Indeed, this must have snuck by us.  Using the Way Back Machine, I can get at the old content of that page: 
https://web.archive.org/web/20180326121351/http://www.mosaic-web.org/go/teachingRlicense.html

Here's the text:

> Teaching Statistics Using R: An Instructors Guide by [Randall Pruim, Nicholas J. Horton and Daniel Kaplan](https://web.archive.org/web/20180326121351/http://www.mosaic-web.org/teachingR) is licensed under a [Creative Commons Attribution 3.0 Unported License](https://web.archive.org/web/20180326121351/http://creativecommons.org/licenses/by/3.0/).
Based on a work at [www.mosaic-web.org](https://web.archive.org/web/20180326121351/http://www.mosaic-web.org/teachingR).

I'll see if I can get a similar page up on our new website.

**Comment by rpruim** [comment]
I've rebuilt the page at http://www.mosaic-web.org/go/teachingRlicense.html
