### ISSUE TITLE
update to Student Guide (formerly Compendium)

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/LittleBooks#7]
I added a chapter introducing RStudio, as well as new examples of msummary(), derivedFactor(), and how to create a table from summary statistics.  Comments and suggestions welcomed.

**Comment by rpruim** [comment]
I suggest that we rename some folders and files to reflect the title change.  Perhaps
- Compendium -> StudentGuide

**Comment by nicholasjhorton** [comment]
This sounds like a good plan.

Nick

**Comment by rpruim** [comment]
Renaming is done and pushed.
