### ISSUE TITLE
Make sure each little book includes indication of R version and mosaic package version used

### ISSUE THREAD

**Issue by rpruim** [ProjectMOSAIC/LittleBooks#8]
Especially if we uncouple little book releases from package releases, it would be good if these self-documented the state of things at the time they were compiled.

**Comment by nicholasjhorton** [comment]
Do you have existing code which grabs the mosaic version number?  

This needs to be added to Starting/FrontMatter.Rnw.  At present it has the following:

This document was created on
\today, using \pkg{knitr} and
\Sexpr{R.version.string}.

**Comment by rpruim** [comment]
This will do the trick:

``` r
> packageVersion("mosaic")
[1] ‘0.9.3.9002’
```

**Comment by nicholasjhorton** [comment]
Done (and pushed).

**Comment by rpruim** [comment]
I've tweaked this a bit (but not enough, as I see there is a typo to go fix)

![image](https://cloud.githubusercontent.com/assets/722231/7694272/38d6f8fe-fe32-11e4-8e5f-1b45662174d1.png)
