### ISSUE TITLE
Require more requires

### ISSUE THREAD

**Issue by kcrisman** [ProjectMOSAIC/LittleBooks#9]
Hi all, I was suggesting some MOSAIC resources to people and noticed that I got an error while doing this command in RStudio (in https://github.com/ProjectMOSAIC/LittleBooks/blob/master/Starting/EarlyRExamples.Rnw):

```
<<births1,out.width=".8\\textwidth",fig.width=5>>=
xyplot(births ~ dayofyear, data=Births78)
@
```

The reason is, of course, that I didn't load the mosaicData package like is done a few lines down.  So I have two suggestions:
- Naturally, make this (first) example work properly
- More importantly, make it really clear why this is necessary there to the beginner - there is just a comment in the code itself!  For instance, in the sentence
  
  The \dataframe{Births78} data set contains the number of births in the United States for each day of 1978.  

it could be also explained how this works within R.

My apologies if this is in another issue - I didn't see it, anyway.  And maybe you ask for it to be loaded earlier in the text?  I didn't see it, though (granted, I was skimming); then again, people might start using such a book anywhere, n'est pas?  Maybe _every_ example should have the load or require, though that might be too tedious...  Looking good!

**Comment by rpruim** [comment]
Two things on this front:
- We've requested from CRAN that we be allowed to make `mosaicData` a dependency.  We'll see.
- Now that the `mosaic` issues are mostly addressed, I'll spend at least a little time looking at the _Starting_ document.

**Comment by kcrisman** [comment]
Since it apparently installed when I installed `mosaic` itself (I didn't separately download it in this R installation), hopefully they'll be fairly open to that.

**Comment by kcrisman** [comment]
For all these documents, please feel free to message me if you need some proofreading or something from someone familiar with the material, but not so much as to not catch things.

**Comment by nicholasjhorton** [comment]
This has now been addressed.
